### ISSUE TITLE
Bars completely go blank when changed to any configuration other than the default

### ISSUE THREAD

**Issue by TwilightSlick** [stuerp/foo_vis_spectrum_analyzer#22]
Version of the component is 0.7.0.0.
Foobar version is 2.1.2, 32-bit, running on Windows 10 22H2.
I am using the default UI, not Columns UI. However, this same behavior also occurs upon switching to Columns UI.

Upon a fresh configuration of this version, the visualization works as expected.
However, once I start changing settings (i.e. octaves to linear, changing bar colors, etc.) no bars display, only the background.
I've tried reinstalling multiple times. Reverting back to 0.6.0.3 will change the configs back to defaults, then I can reconfigure. But then the bars go blank immediately upon upgrading to 0.7.0.0, which is what happened the first time.

**Comment by stuerp** [comment]
Thank you for the report. Would you mind attaching the component configuration file so that I can examine which value causes the problem?

**Comment by TwilightSlick** [comment]
Where is that configuration file stored? I've looked in the appdata folder and can't find it.

**Comment by stuerp** [comment]
Erhm... that's a very good question. Because the config does not go through the standard foobar2000 settings dialog I just get handed a blob of data by fb2k. I assumed it read and wrote it to a .cfg file in the fb2k profile but apparently not.

I'll ask around. 

I did encounter a deadlock scenario in the current release myself which should be solved in the next beta, if you can wait for it.

**Comment by stuerp** [comment]
@TwilightSlick , could you please try the latest beta and see if it solves your problem before I go on a bug hunt?

**Comment by TwilightSlick** [comment]
I just updated, did not reset configuration after updating, still no bars at all, only the background.
